# Generated by Django 5.1.7 on 2025-04-10 05:50

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0009_merge_20250409_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='featured_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='cars/featured/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedán'), ('suv', 'SUV'), ('sports', 'Deportivo'), ('pickup', 'Pickup')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Car360Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='cars/360/')),
                ('angle', models.IntegerField(help_text='Ángulo de la imagen (0-359)')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_360', to='autos.car')),
            ],
            options={
                'ordering': ['angle'],
            },
        ),
    ]
